boot.o: boot.S multiboot.h x86_desc.h types.h interrupt_table.h \
  interrupt_handler.h
interrupt_handler.o: interrupt_handler.S interrupt_handler.h x86_desc.h \
  types.h
syscall_handler.o: syscall_handler.S
x86_desc.o: x86_desc.S x86_desc.h types.h
fs_module.o: fs_module.c fs_module.h lib.h types.h system_call.h
i8259.o: i8259.c i8259.h types.h lib.h
interrupt_table.o: interrupt_table.c interrupt_table.h x86_desc.h types.h \
  interrupt_handler.h lib.h i8259.h syscall_handler.h system_call.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h pit.h \
  system_call.h rtc.h keyboard.h debug.h tests.h paging.h fs_module.h
keyboard.o: keyboard.c keyboard.h types.h system_call.h i8259.h lib.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h
pit.o: pit.c pit.h types.h system_call.h i8259.h lib.h scheduler.h \
  paging.h fs_module.h x86_desc.h rtc.h keyboard.h
rtc.o: rtc.c rtc.h types.h system_call.h i8259.h lib.h
scheduler.o: scheduler.c scheduler.h system_call.h types.h pit.h paging.h \
  fs_module.h lib.h x86_desc.h rtc.h keyboard.h
system_call.o: system_call.c system_call.h types.h fs_module.h lib.h \
  x86_desc.h rtc.h keyboard.h paging.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h rtc.h system_call.h \
  keyboard.h fs_module.h paging.h
